name: trendsoccer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.1
  go_router: ^17.2.0
  dio: ^5.9.2
  supabase_flutter: ^2.12.2
  google_fonts: ^8.0.2
  flutter_svg: ^2.0.10  # SVG 지원 추가
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.3
  build_runner: ^2.13.1

flutter:
  uses-material-design: true

  assets:
    # League Icons
    - assets/images/leagues/premier_league.svg
    - assets/images/leagues/laliga.svg
    - assets/images/leagues/bundesliga.svg
    - assets/images/leagues/serie_a.svg
    - assets/images/leagues/ligue_1.svg
    - assets/images/leagues/champions_league.svg
    - assets/images/leagues/europa_league.svg
    - assets/images/leagues/eredivisie.svg
    - assets/images/leagues/k_league.svg
    - assets/images/leagues/j1_league.svg
    - assets/images/leagues/mls.svg
    - assets/images/leagues/kbo.svg
    - assets/images/leagues/mlb.svg
    - assets/images/leagues/npb.svg
    - assets/images/leagues/cpbl.svg
    
    # App Logos
    - assets/images/logos/logo_horizon_black.svg
    - assets/images/logos/logo_horizon_gradient.svg
    - assets/images/logos/logo_horizon_white.svg
    - assets/images/logos/logo_vertical_black.svg
    - assets/images/logos/logo_vertical_gradient.svg
    - assets/images/logos/logo_vertical_white.svg
