name: trendsoccer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.1
  go_router: ^17.2.0
  dio: ^5.7.0
  supabase_flutter: ^2.8.0
  flutter_dotenv: ^5.2.1
  flutter_svg: ^2.0.10  # SVG support
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.5
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - .env

    # Logos
    - assets/images/tsLogo/dark/
    - assets/images/tsLogo/light/

    # League Icons (Analysis)
    - assets/images/league/icon/dark/
    - assets/images/league/icon/light/

    # League Logos (Report)
    - assets/images/league/logo/dark/
    - assets/images/league/logo/light/

    # Social login symbols (Auth)
    - assets/images/social/

    # UI icons
    - assets/images/icon/foundation/
    - assets/images/icon/sport/

    # Plan ticket images (Menu)
    - assets/images/plan/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard/Pretendard-Thin.otf
          weight: 100
        - asset: assets/fonts/Pretendard/Pretendard-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Pretendard/Pretendard-Light.otf
          weight: 300
        - asset: assets/fonts/Pretendard/Pretendard-Regular.otf
          weight: 400
        - asset: assets/fonts/Pretendard/Pretendard-Medium.otf
          weight: 500
        - asset: assets/fonts/Pretendard/Pretendard-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Pretendard/Pretendard-Bold.otf
          weight: 700
        - asset: assets/fonts/Pretendard/Pretendard-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Pretendard/Pretendard-Black.otf
          weight: 900
