name: trendsoccer
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.1
  go_router: ^17.2.0
  dio: ^5.9.2
  supabase_flutter: ^2.12.2
  google_fonts: ^8.0.2
  flutter_svg: ^2.0.10  # SVG 지원 추가
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^4.0.3
  build_runner: ^2.13.1

flutter:
  uses-material-design: true

  assets:
    # Logos
    - assets/images/logos/

    # League Icons (Analysis용)
    - assets/images/leagues/icon/dark/

    # League Logos (Report용)
    - assets/images/leagues/logo/dark/
    - assets/images/leagues/logo/light/
