import 'package:trendsoccer/features/trend/trend_dummy_data.dart';
import 'package:trendsoccer/shared/widgets/combo/combo_card.dart';
import 'package:trendsoccer/shared/widgets/combo/combo_status_badge.dart';
import 'package:trendsoccer/shared/widgets/combo/combo_type_badge.dart';

final List<AnalysisCardData> premiumPickDummy = [
  AnalysisCardData(
    matchId: 'pp1',
    leagueId: 'champions_league',
    leagueName: '챔피언스리그',
    date: '05.11',
    homeTeam: '바르셀로나',
    awayTeam: '바이에른',
    matchTime: '21:00',
    isPremiumPick: true,
    pickDirection: 'home',
    winRate: '72%',
    sport: 'soccer',
  ),
  AnalysisCardData(
    matchId: 'pp2',
    leagueId: 'premier_league',
    leagueName: '프리미어리그',
    date: '05.11',
    homeTeam: '아스날',
    awayTeam: '첼시',
    matchTime: '18:30',
    isPremiumPick: true,
    pickDirection: 'away',
    winRate: '65%',
    sport: 'soccer',
  ),
  AnalysisCardData(
    matchId: 'pp3',
    leagueId: 'serie_a',
    leagueName: '세리에A',
    date: '05.11',
    homeTeam: '유벤투스',
    awayTeam: 'AC 밀란',
    matchTime: '19:00',
    isPremiumPick: true,
    pickDirection: 'draw',
    winRate: '58%',
    sport: 'soccer',
  ),
  AnalysisCardData(
    matchId: 'pp4',
    leagueId: 'laliga',
    leagueName: '라리가',
    date: '05.11',
    homeTeam: '레알 마드리드',
    awayTeam: '아틀레티코',
    matchTime: '22:00',
    isPremiumPick: true,
    pickDirection: 'home',
    winRate: '70%',
    sport: 'soccer',
  ),
  AnalysisCardData(
    matchId: 'pp5',
    leagueId: 'bundesliga',
    leagueName: '분데스리가',
    date: '05.12',
    homeTeam: '바이에른',
    awayTeam: '도르트문트',
    matchTime: '20:30',
    isPremiumPick: true,
    pickDirection: 'home',
    winRate: '68%',
    sport: 'soccer',
  ),
];

class ComboDayData {
  const ComboDayData({
    required this.dateLabel,
    required this.dateTitle,
    required this.comboCountText,
    required this.comboCount,
    required this.accuracy,
    required this.avgOdds,
    required this.safeHitRate,
    required this.safeHitDetail,
    required this.highOddsHitRate,
    required this.highOddsHitDetail,
    required this.combos,
  });

  final String dateLabel;
  final String dateTitle;
  final String comboCountText;
  final int comboCount;
  final String accuracy;
  final String avgOdds;
  final String safeHitRate;
  final String safeHitDetail;
  final String highOddsHitRate;
  final String highOddsHitDetail;
  final List<ComboCardDummy> combos;
}

class ComboCardDummy {
  const ComboCardDummy({
    required this.leagueId,
    required this.comboCount,
    required this.comboType,
    required this.status,
    required this.matches,
    required this.aiReport,
    required this.totalOdds,
    required this.confidence,
  });

  final String leagueId;
  final int comboCount;
  final ComboType comboType;
  final ComboStatus status;
  final List<ComboMatchRowData> matches;
  final String aiReport;
  final String totalOdds;
  final String confidence;
}

final List<ComboDayData> comboDaysDummy = [
  ComboDayData(
    dateLabel: '오늘',
    dateTitle: '5월 11일 (일)',
    comboCountText: '4개 AI 조합 분석 완료',
    comboCount: 4,
    accuracy: '-',
    avgOdds: '-',
    safeHitRate: '-',
    safeHitDetail: '(0/2)',
    highOddsHitRate: '-',
    highOddsHitDetail: '(0/2)',
    combos: [
      ComboCardDummy(
        leagueId: 'kbo',
        comboCount: 2,
        comboType: ComboType.safe,
        status: ComboStatus.inProgress,
        matches: [
          const ComboMatchRowData(
            homeTeam: 'LG 트윈스',
            awayTeam: 'KT 위즈',
            predictTeam: 'LG 트윈스',
            predictDirection: '홈',
            odds: '1.55',
            winRate: '68%',
            winRateRatio: 0.68,
            comment: '최근 5연승 홈팀 우세',
          ),
          const ComboMatchRowData(
            homeTeam: '삼성',
            awayTeam: '두산',
            predictTeam: '삼성',
            predictDirection: '홈',
            odds: '1.70',
            winRate: '62%',
            winRateRatio: 0.62,
            comment: '홈 구장 이점 활용',
          ),
        ],
        aiReport:
            'LG 트윈스와 삼성 모두 홈 구장 이점을 최대한 활용할 수 있는 매치업입니다. 두 팀 모두 최근 10경기 홈 승률이 65% 이상으로, 안전형 조합에 적합합니다.',
        totalOdds: '2.64',
        confidence: '87%',
      ),
      ComboCardDummy(
        leagueId: 'mlb',
        comboCount: 2,
        comboType: ComboType.highOdds,
        status: ComboStatus.inProgress,
        matches: [
          const ComboMatchRowData(
            homeTeam: '양키스',
            awayTeam: '레드삭스',
            predictTeam: '레드삭스',
            predictDirection: '원정',
            odds: '2.30',
            winRate: '48%',
            winRateRatio: 0.48,
            comment: '선발 투수 매치업 원정 유리',
          ),
          const ComboMatchRowData(
            homeTeam: '다저스',
            awayTeam: '자이언츠',
            predictTeam: '다저스',
            predictDirection: '홈',
            odds: '1.45',
            winRate: '71%',
            winRateRatio: 0.71,
            comment: '홈 승률 압도적',
          ),
        ],
        aiReport:
            '레드삭스 선발 투수의 최근 5경기 ERA 2.80으로 원정에서도 안정적이며, 다저스는 홈 구장에서 시즌 승률 72%를 기록 중입니다.',
        totalOdds: '3.34',
        confidence: '62%',
      ),
      ComboCardDummy(
        leagueId: 'npb',
        comboCount: 2,
        comboType: ComboType.safe,
        status: ComboStatus.inProgress,
        matches: [
          const ComboMatchRowData(
            homeTeam: '요미우리',
            awayTeam: '한신',
            predictTeam: '요미우리',
            predictDirection: '홈',
            odds: '1.50',
            winRate: '66%',
            winRateRatio: 0.66,
            comment: '홈 도쿄돔 이점 활용',
          ),
          const ComboMatchRowData(
            homeTeam: '소프트뱅크',
            awayTeam: '라쿠텐',
            predictTeam: '소프트뱅크',
            predictDirection: '홈',
            odds: '1.40',
            winRate: '72%',
            winRateRatio: 0.72,
            comment: '에이스 선발 등판',
          ),
        ],
        aiReport:
            '요미우리와 소프트뱅크 모두 홈 구장 강세가 뚜렷하며, 선발 투수 매치업에서도 유리한 조건입니다.',
        totalOdds: '2.10',
        confidence: '85%',
      ),
      ComboCardDummy(
        leagueId: 'kbo',
        comboCount: 3,
        comboType: ComboType.highOdds,
        status: ComboStatus.inProgress,
        matches: [
          const ComboMatchRowData(
            homeTeam: 'NC',
            awayTeam: 'SSG',
            predictTeam: 'SSG',
            predictDirection: '원정',
            odds: '2.10',
            winRate: '52%',
            winRateRatio: 0.52,
            comment: '원정 SSG 최근 상승세',
          ),
          const ComboMatchRowData(
            homeTeam: '키움',
            awayTeam: '롯데',
            predictTeam: '롯데',
            predictDirection: '원정',
            odds: '2.40',
            winRate: '46%',
            winRateRatio: 0.46,
            comment: '롯데 원정 선발 우위',
          ),
          const ComboMatchRowData(
            homeTeam: '두산',
            awayTeam: 'LG 트윈스',
            predictTeam: 'LG 트윈스',
            predictDirection: '원정',
            odds: '1.85',
            winRate: '56%',
            winRateRatio: 0.56,
            comment: 'LG 최근 원정 4연승',
          ),
        ],
        aiReport:
            'SSG, 롯데, LG 모두 최근 원정 성적이 좋아 고배당 원정 조합을 구성했습니다.',
        totalOdds: '9.32',
        confidence: '48%',
      ),
    ],
  ),
  ComboDayData(
    dateLabel: '5.10',
    dateTitle: '5월 10일 (토)',
    comboCountText: '3개 AI 조합 분석 완료',
    comboCount: 3,
    accuracy: '67%',
    avgOdds: '2.90',
    safeHitRate: '100%',
    safeHitDetail: '(2/2)',
    highOddsHitRate: '0%',
    highOddsHitDetail: '(0/1)',
    combos: [
      ComboCardDummy(
        leagueId: 'kbo',
        comboCount: 2,
        comboType: ComboType.safe,
        status: ComboStatus.hit,
        matches: [
          ComboMatchRowData(
            homeTeam: 'NC',
            awayTeam: 'SSG',
            predictTeam: 'SSG',
            predictDirection: '원정',
            odds: '1.80',
            winRate: '58%',
            winRateRatio: 0.58,
            comment: '원정 SSG 최근 폼 상승',
            matchResult: ComboStatus.hit,
            homeScore: '3',
            awayScore: '6',
          ),
          ComboMatchRowData(
            homeTeam: '키움',
            awayTeam: '롯데',
            predictTeam: '키움',
            predictDirection: '홈',
            odds: '1.50',
            winRate: '65%',
            winRateRatio: 0.65,
            comment: '홈 구장 강세',
            matchResult: ComboStatus.hit,
            homeScore: '5',
            awayScore: '2',
          ),
        ],
        aiReport:
            'SSG 원정 최근 폼이 상승세이며, 키움은 홈 구장 강세가 뚜렷합니다. 두 경기 모두 선발 투수 매치업에서 유리한 조건입니다.',
        totalOdds: '2.70',
        confidence: '91%',
      ),
      ComboCardDummy(
        leagueId: 'mlb',
        comboCount: 2,
        comboType: ComboType.highOdds,
        status: ComboStatus.miss,
        matches: [
          ComboMatchRowData(
            homeTeam: '양키스',
            awayTeam: '레드삭스',
            predictTeam: '레드삭스',
            predictDirection: '원정',
            odds: '2.20',
            winRate: '48%',
            winRateRatio: 0.48,
            comment: '선발 투수 원정 유리',
            matchResult: ComboStatus.miss,
            homeScore: '5',
            awayScore: '2',
          ),
          ComboMatchRowData(
            homeTeam: '메츠',
            awayTeam: '필리스',
            predictTeam: '필리스',
            predictDirection: '원정',
            odds: '1.90',
            winRate: '54%',
            winRateRatio: 0.54,
            comment: '필리스 원정 폼 상승',
            matchResult: ComboStatus.hit,
            homeScore: '1',
            awayScore: '4',
          ),
        ],
        aiReport:
            '레드삭스와 필리스의 원정 전력을 기반으로 고배당 조합을 구성했습니다.',
        totalOdds: '4.18',
        confidence: '55%',
      ),
      ComboCardDummy(
        leagueId: 'kbo',
        comboCount: 2,
        comboType: ComboType.safe,
        status: ComboStatus.hit,
        matches: [
          ComboMatchRowData(
            homeTeam: '삼성',
            awayTeam: '두산',
            predictTeam: '삼성',
            predictDirection: '홈',
            odds: '1.55',
            winRate: '64%',
            winRateRatio: 0.64,
            comment: '홈 구장 대구 이점',
            matchResult: ComboStatus.hit,
            homeScore: '4',
            awayScore: '1',
          ),
          ComboMatchRowData(
            homeTeam: 'LG 트윈스',
            awayTeam: 'KT 위즈',
            predictTeam: 'LG 트윈스',
            predictDirection: '홈',
            odds: '1.45',
            winRate: '68%',
            winRateRatio: 0.68,
            comment: '잠실 홈 연승 행진',
            matchResult: ComboStatus.hit,
            homeScore: '6',
            awayScore: '3',
          ),
        ],
        aiReport:
            '삼성 대구 홈 이점과 LG 잠실 연승 기록을 바탕으로 안전형 조합을 구성했습니다.',
        totalOdds: '2.25',
        confidence: '89%',
      ),
    ],
  ),
  ComboDayData(
    dateLabel: '5.9',
    dateTitle: '5월 9일 (금)',
    comboCountText: '3개 AI 조합 분석 완료',
    comboCount: 3,
    accuracy: '33%',
    avgOdds: '3.20',
    safeHitRate: '50%',
    safeHitDetail: '(1/2)',
    highOddsHitRate: '0%',
    highOddsHitDetail: '(0/1)',
    combos: [
      ComboCardDummy(
        leagueId: 'kbo',
        comboCount: 2,
        comboType: ComboType.safe,
        status: ComboStatus.miss,
        matches: [
          ComboMatchRowData(
            homeTeam: 'NC',
            awayTeam: 'SSG',
            predictTeam: 'NC',
            predictDirection: '홈',
            odds: '1.65',
            winRate: '60%',
            winRateRatio: 0.60,
            comment: '홈 구장 이점',
            matchResult: ComboStatus.miss,
            homeScore: '2',
            awayScore: '5',
          ),
          ComboMatchRowData(
            homeTeam: '키움',
            awayTeam: '롯데',
            predictTeam: '키움',
            predictDirection: '홈',
            odds: '1.50',
            winRate: '64%',
            winRateRatio: 0.64,
            comment: '선발 투수 우위',
            matchResult: ComboStatus.hit,
            homeScore: '4',
            awayScore: '1',
          ),
        ],
        aiReport:
            'NC 홈 구장 이점과 키움의 선발 투수 ERA 3.10 기반으로 두 경기 홈팀 우세를 예측합니다.',
        totalOdds: '2.48',
        confidence: '75%',
      ),
      ComboCardDummy(
        leagueId: 'kbo',
        comboCount: 2,
        comboType: ComboType.safe,
        status: ComboStatus.hit,
        matches: [
          ComboMatchRowData(
            homeTeam: 'LG 트윈스',
            awayTeam: '두산',
            predictTeam: 'LG 트윈스',
            predictDirection: '홈',
            odds: '1.50',
            winRate: '67%',
            winRateRatio: 0.67,
            comment: '더비 홈팀 압도',
            matchResult: ComboStatus.hit,
            homeScore: '5',
            awayScore: '1',
          ),
          ComboMatchRowData(
            homeTeam: '삼성',
            awayTeam: 'KT 위즈',
            predictTeam: '삼성',
            predictDirection: '홈',
            odds: '1.60',
            winRate: '62%',
            winRateRatio: 0.62,
            comment: '홈 선발 ERA 2.90',
            matchResult: ComboStatus.hit,
            homeScore: '3',
            awayScore: '2',
          ),
        ],
        aiReport:
            'LG 더비 홈 강세와 삼성 선발 투수 안정감을 기반으로 안전형 조합을 구성했습니다.',
        totalOdds: '2.40',
        confidence: '86%',
      ),
      ComboCardDummy(
        leagueId: 'mlb',
        comboCount: 2,
        comboType: ComboType.highOdds,
        status: ComboStatus.miss,
        matches: [
          ComboMatchRowData(
            homeTeam: '다저스',
            awayTeam: '자이언츠',
            predictTeam: '자이언츠',
            predictDirection: '원정',
            odds: '2.80',
            winRate: '40%',
            winRateRatio: 0.40,
            comment: '자이언츠 원정 최근 3연승',
            matchResult: ComboStatus.miss,
            homeScore: '6',
            awayScore: '2',
          ),
          ComboMatchRowData(
            homeTeam: '양키스',
            awayTeam: '레드삭스',
            predictTeam: '양키스',
            predictDirection: '홈',
            odds: '1.35',
            winRate: '74%',
            winRateRatio: 0.74,
            comment: '양키스 홈 시즌 승률 1위',
            matchResult: ComboStatus.hit,
            homeScore: '4',
            awayScore: '1',
          ),
        ],
        aiReport:
            '자이언츠 원정 연승 모멘텀과 양키스 홈 절대 우위를 조합한 고배당 구성입니다.',
        totalOdds: '3.78',
        confidence: '52%',
      ),
    ],
  ),
  ComboDayData(
    dateLabel: '5.8',
    dateTitle: '5월 8일 (목)',
    comboCountText: '4개 AI 조합 분석 완료',
    comboCount: 4,
    accuracy: '75%',
    avgOdds: '2.80',
    safeHitRate: '100%',
    safeHitDetail: '(3/3)',
    highOddsHitRate: '0%',
    highOddsHitDetail: '(0/1)',
    combos: [
      ComboCardDummy(
        leagueId: 'kbo',
        comboCount: 2,
        comboType: ComboType.safe,
        status: ComboStatus.hit,
        matches: [
          ComboMatchRowData(
            homeTeam: 'LG 트윈스',
            awayTeam: '두산',
            predictTeam: 'LG 트윈스',
            predictDirection: '홈',
            odds: '1.45',
            winRate: '70%',
            winRateRatio: 0.70,
            comment: '홈 연승 행진',
            matchResult: ComboStatus.hit,
            homeScore: '6',
            awayScore: '2',
          ),
          ComboMatchRowData(
            homeTeam: '삼성',
            awayTeam: 'KT 위즈',
            predictTeam: '삼성',
            predictDirection: '홈',
            odds: '1.60',
            winRate: '63%',
            winRateRatio: 0.63,
            comment: '상대 전적 유리',
            matchResult: ComboStatus.hit,
            homeScore: '5',
            awayScore: '3',
          ),
        ],
        aiReport:
            'LG 트윈스 홈 연승 기록과 삼성의 상대 전적 우위를 바탕으로 안전형 조합을 구성했습니다.',
        totalOdds: '2.32',
        confidence: '88%',
      ),
      ComboCardDummy(
        leagueId: 'mlb',
        comboCount: 2,
        comboType: ComboType.safe,
        status: ComboStatus.hit,
        matches: [
          ComboMatchRowData(
            homeTeam: '다저스',
            awayTeam: '자이언츠',
            predictTeam: '다저스',
            predictDirection: '홈',
            odds: '1.40',
            winRate: '72%',
            winRateRatio: 0.72,
            comment: '다저스 홈 7연승',
            matchResult: ComboStatus.hit,
            homeScore: '5',
            awayScore: '2',
          ),
          ComboMatchRowData(
            homeTeam: '양키스',
            awayTeam: '레드삭스',
            predictTeam: '양키스',
            predictDirection: '홈',
            odds: '1.55',
            winRate: '65%',
            winRateRatio: 0.65,
            comment: '양키스 선발 ERA 2.50',
            matchResult: ComboStatus.hit,
            homeScore: '3',
            awayScore: '1',
          ),
        ],
        aiReport:
            '다저스 홈 연승과 양키스 선발 안정감을 기반으로 MLB 안전형 조합을 구성했습니다.',
        totalOdds: '2.17',
        confidence: '88%',
      ),
      ComboCardDummy(
        leagueId: 'kbo',
        comboCount: 2,
        comboType: ComboType.highOdds,
        status: ComboStatus.miss,
        matches: [
          ComboMatchRowData(
            homeTeam: 'NC',
            awayTeam: 'SSG',
            predictTeam: 'SSG',
            predictDirection: '원정',
            odds: '2.10',
            winRate: '52%',
            winRateRatio: 0.52,
            comment: 'SSG 원정 최근 폼',
            matchResult: ComboStatus.miss,
            homeScore: '4',
            awayScore: '2',
          ),
          ComboMatchRowData(
            homeTeam: '롯데',
            awayTeam: '키움',
            predictTeam: '키움',
            predictDirection: '원정',
            odds: '2.30',
            winRate: '47%',
            winRateRatio: 0.47,
            comment: '키움 원정 선발 우위',
            matchResult: ComboStatus.miss,
            homeScore: '5',
            awayScore: '3',
          ),
        ],
        aiReport:
            'SSG와 키움의 원정 잠재력을 기반으로 고배당 조합을 구성했습니다.',
        totalOdds: '4.83',
        confidence: '45%',
      ),
      ComboCardDummy(
        leagueId: 'npb',
        comboCount: 2,
        comboType: ComboType.safe,
        status: ComboStatus.hit,
        matches: [
          ComboMatchRowData(
            homeTeam: '요미우리',
            awayTeam: '한신',
            predictTeam: '요미우리',
            predictDirection: '홈',
            odds: '1.45',
            winRate: '69%',
            winRateRatio: 0.69,
            comment: '도쿄돔 홈 강세',
            matchResult: ComboStatus.hit,
            homeScore: '3',
            awayScore: '1',
          ),
          ComboMatchRowData(
            homeTeam: '소프트뱅크',
            awayTeam: '라쿠텐',
            predictTeam: '소프트뱅크',
            predictDirection: '홈',
            odds: '1.50',
            winRate: '67%',
            winRateRatio: 0.67,
            comment: '에이스 등판 기대',
            matchResult: ComboStatus.hit,
            homeScore: '6',
            awayScore: '2',
          ),
        ],
        aiReport:
            '요미우리 도쿄돔 홈 이점과 소프트뱅크 에이스 등판 조건을 활용한 NPB 안전형 조합입니다.',
        totalOdds: '2.18',
        confidence: '87%',
      ),
    ],
  ),
  ComboDayData(
    dateLabel: '5.7',
    dateTitle: '5월 7일 (수)',
    comboCountText: '2개 AI 조합 분석 완료',
    comboCount: 2,
    accuracy: '50%',
    avgOdds: '3.50',
    safeHitRate: '100%',
    safeHitDetail: '(1/1)',
    highOddsHitRate: '0%',
    highOddsHitDetail: '(0/1)',
    combos: [
      ComboCardDummy(
        leagueId: 'mlb',
        comboCount: 2,
        comboType: ComboType.highOdds,
        status: ComboStatus.partial,
        matches: [
          ComboMatchRowData(
            homeTeam: '양키스',
            awayTeam: '레드삭스',
            predictTeam: '레드삭스',
            predictDirection: '원정',
            odds: '2.10',
            winRate: '50%',
            winRateRatio: 0.50,
            comment: '선발 매치업 접전',
            matchResult: ComboStatus.hit,
            homeScore: '3',
            awayScore: '5',
          ),
          ComboMatchRowData(
            homeTeam: '다저스',
            awayTeam: '자이언츠',
            predictTeam: '다저스',
            predictDirection: '홈',
            odds: '1.40',
            winRate: '72%',
            winRateRatio: 0.72,
            comment: '홈 압도적 전적',
            matchResult: ComboStatus.miss,
            homeScore: '1',
            awayScore: '3',
          ),
        ],
        aiReport:
            '레드삭스 선발 매치업과 다저스 홈 전적을 기반으로 고배당 조합을 구성했습니다.',
        totalOdds: '2.94',
        confidence: '65%',
      ),
      ComboCardDummy(
        leagueId: 'kbo',
        comboCount: 2,
        comboType: ComboType.safe,
        status: ComboStatus.hit,
        matches: [
          ComboMatchRowData(
            homeTeam: 'LG 트윈스',
            awayTeam: '롯데',
            predictTeam: 'LG 트윈스',
            predictDirection: '홈',
            odds: '1.40',
            winRate: '71%',
            winRateRatio: 0.71,
            comment: '잠실 홈 절대 강세',
            matchResult: ComboStatus.hit,
            homeScore: '7',
            awayScore: '2',
          ),
          ComboMatchRowData(
            homeTeam: '삼성',
            awayTeam: 'NC',
            predictTeam: '삼성',
            predictDirection: '홈',
            odds: '1.55',
            winRate: '64%',
            winRateRatio: 0.64,
            comment: '대구 홈 이점 최대화',
            matchResult: ComboStatus.hit,
            homeScore: '4',
            awayScore: '1',
          ),
        ],
        aiReport:
            'LG 잠실 홈 강세와 삼성 대구 이점을 활용한 KBO 안전형 조합입니다.',
        totalOdds: '2.17',
        confidence: '90%',
      ),
    ],
  ),
  ComboDayData(
    dateLabel: '5.6',
    dateTitle: '5월 6일 (화)',
    comboCountText: '3개 AI 조합 분석 완료',
    comboCount: 3,
    accuracy: '67%',
    avgOdds: '2.60',
    safeHitRate: '100%',
    safeHitDetail: '(2/2)',
    highOddsHitRate: '0%',
    highOddsHitDetail: '(0/1)',
    combos: [
      ComboCardDummy(
        leagueId: 'npb',
        comboCount: 2,
        comboType: ComboType.safe,
        status: ComboStatus.hit,
        matches: [
          ComboMatchRowData(
            homeTeam: '요미우리',
            awayTeam: '한신',
            predictTeam: '요미우리',
            predictDirection: '홈',
            odds: '1.55',
            winRate: '66%',
            winRateRatio: 0.66,
            comment: '홈 도쿄돔 이점',
            matchResult: ComboStatus.hit,
            homeScore: '4',
            awayScore: '2',
          ),
          ComboMatchRowData(
            homeTeam: '소프트뱅크',
            awayTeam: '라쿠텐',
            predictTeam: '소프트뱅크',
            predictDirection: '홈',
            odds: '1.45',
            winRate: '69%',
            winRateRatio: 0.69,
            comment: '선발 에이스 등판',
            matchResult: ComboStatus.hit,
            homeScore: '7',
            awayScore: '1',
          ),
        ],
        aiReport:
            '요미우리 도쿄돔 홈 이점과 소프트뱅크 에이스 등판으로 두 경기 모두 홈팀 우세 조건입니다.',
        totalOdds: '2.25',
        confidence: '90%',
      ),
      ComboCardDummy(
        leagueId: 'kbo',
        comboCount: 2,
        comboType: ComboType.safe,
        status: ComboStatus.hit,
        matches: [
          ComboMatchRowData(
            homeTeam: 'LG 트윈스',
            awayTeam: 'KT 위즈',
            predictTeam: 'LG 트윈스',
            predictDirection: '홈',
            odds: '1.45',
            winRate: '68%',
            winRateRatio: 0.68,
            comment: '잠실 홈 연승',
            matchResult: ComboStatus.hit,
            homeScore: '5',
            awayScore: '3',
          ),
          ComboMatchRowData(
            homeTeam: '두산',
            awayTeam: 'NC',
            predictTeam: '두산',
            predictDirection: '홈',
            odds: '1.55',
            winRate: '63%',
            winRateRatio: 0.63,
            comment: '두산 홈 최근 폼',
            matchResult: ComboStatus.hit,
            homeScore: '4',
            awayScore: '2',
          ),
        ],
        aiReport:
            'LG 잠실 연승과 두산 홈 최근 폼을 활용한 KBO 안전형 조합입니다.',
        totalOdds: '2.25',
        confidence: '87%',
      ),
      ComboCardDummy(
        leagueId: 'mlb',
        comboCount: 2,
        comboType: ComboType.highOdds,
        status: ComboStatus.miss,
        matches: [
          ComboMatchRowData(
            homeTeam: '메츠',
            awayTeam: '필리스',
            predictTeam: '필리스',
            predictDirection: '원정',
            odds: '2.10',
            winRate: '52%',
            winRateRatio: 0.52,
            comment: '필리스 원정 폼 상승',
            matchResult: ComboStatus.miss,
            homeScore: '4',
            awayScore: '2',
          ),
          ComboMatchRowData(
            homeTeam: '다저스',
            awayTeam: '자이언츠',
            predictTeam: '자이언츠',
            predictDirection: '원정',
            odds: '2.60',
            winRate: '42%',
            winRateRatio: 0.42,
            comment: '자이언츠 원정 반등 기대',
            matchResult: ComboStatus.miss,
            homeScore: '7',
            awayScore: '3',
          ),
        ],
        aiReport:
            '필리스와 자이언츠의 원정 전력 분석 기반으로 고배당 MLB 조합을 구성했습니다.',
        totalOdds: '5.46',
        confidence: '42%',
      ),
    ],
  ),
  ComboDayData(
    dateLabel: '5.5',
    dateTitle: '5월 5일 (월)',
    comboCountText: '2개 AI 조합 분석 완료',
    comboCount: 2,
    accuracy: '100%',
    avgOdds: '2.40',
    safeHitRate: '100%',
    safeHitDetail: '(1/1)',
    highOddsHitRate: '100%',
    highOddsHitDetail: '(1/1)',
    combos: [
      ComboCardDummy(
        leagueId: 'kbo',
        comboCount: 2,
        comboType: ComboType.safe,
        status: ComboStatus.hit,
        matches: [
          ComboMatchRowData(
            homeTeam: 'SSG',
            awayTeam: '롯데',
            predictTeam: 'SSG',
            predictDirection: '홈',
            odds: '1.50',
            winRate: '67%',
            winRateRatio: 0.67,
            comment: '홈 구장 강세',
            matchResult: ComboStatus.hit,
            homeScore: '5',
            awayScore: '2',
          ),
          ComboMatchRowData(
            homeTeam: '두산',
            awayTeam: 'NC',
            predictTeam: '두산',
            predictDirection: '홈',
            odds: '1.60',
            winRate: '62%',
            winRateRatio: 0.62,
            comment: '최근 폼 상승',
            matchResult: ComboStatus.hit,
            homeScore: '4',
            awayScore: '1',
          ),
        ],
        aiReport: 'SSG 홈 구장 강세와 두산의 최근 폼 상승을 반영한 안전형 조합입니다.',
        totalOdds: '2.40',
        confidence: '92%',
      ),
      ComboCardDummy(
        leagueId: 'mlb',
        comboCount: 2,
        comboType: ComboType.highOdds,
        status: ComboStatus.hit,
        matches: [
          ComboMatchRowData(
            homeTeam: '양키스',
            awayTeam: '레드삭스',
            predictTeam: '레드삭스',
            predictDirection: '원정',
            odds: '2.20',
            winRate: '50%',
            winRateRatio: 0.50,
            comment: '레드삭스 선발 ERA 2.60',
            matchResult: ComboStatus.hit,
            homeScore: '3',
            awayScore: '5',
          ),
          ComboMatchRowData(
            homeTeam: '다저스',
            awayTeam: '자이언츠',
            predictTeam: '다저스',
            predictDirection: '홈',
            odds: '1.40',
            winRate: '72%',
            winRateRatio: 0.72,
            comment: '다저스 홈 압도적',
            matchResult: ComboStatus.hit,
            homeScore: '6',
            awayScore: '1',
          ),
        ],
        aiReport:
            '레드삭스 선발 안정감과 다저스 홈 절대 우위를 조합한 고배당 구성입니다.',
        totalOdds: '3.08',
        confidence: '65%',
      ),
    ],
  ),
  ComboDayData(
    dateLabel: '5.4',
    dateTitle: '5월 4일 (일)',
    comboCountText: '조합 없음',
    comboCount: 0,
    accuracy: '-',
    avgOdds: '-',
    safeHitRate: '-',
    safeHitDetail: '(0/0)',
    highOddsHitRate: '-',
    highOddsHitDetail: '(0/0)',
    combos: [],
  ),
];

final List<String> comboDateLabels = [
  '오늘',
  '5.10',
  '5.9',
  '5.8',
  '5.7',
  '5.6',
  '5.5',
  '5.4',
];
